api/urls.py
from rest_framework import routers
from django.conf.urls import url
from .views import DayOffViewSet
from .views import vacation_detail, vacation_list
from .views import user_list, user_detail

day_off_list = DayOffViewSet.as_view({
    'get': 'list',
})
day_off_detail = DayOffViewSet.as_view({
    'get': 'retrieve',
})


urlpatterns = [
    url(r'^users/$', user_list, name='user_list'),
    url(r'^users/(?P<pk>[0-9]+)/$', user_detail, name='user_list'),
    url(r'^day_offs/$', day_off_list, name='day_off_list'),
    url(r'^day_offs/(?P<pk>\d+)/$', day_off_detail, name='day_off_detail'),
    url(r'^vacations/$', vacation_list, name='vacation_list'),
    url(r'^vacations/(?P<pk>[0-9]+)/$', vacation_detail, name='vacation-detail')
]

# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'dayoff', DayOffViewSet)

jsl/vac/urls.py
from django.conf.urls import url
from django.contrib.auth import views

from vac.views import list, menu, vac_docs, login, pulldown

urlpatterns = [
    # 休暇一覧表示
    url(r'^list/$', list.DayOffListView.as_view(), name='vacation_list'),
    # メニュー
    url(r'^$', menu.menu, name='vacation_menu'),
    # 新規休暇届
    url(r'^day_off/add/$', vac_docs.vac_edit, name='day_off_add'),
    # 休暇届修正
    url(r'^day_off/edit/(?P<day_off_id>\d+)$', vac_docs.vac_edit, name='day_off_edit'),
    # 休暇届削除
    url(r'^day_off/del/(?P<day_off_id>\d+)$', vac_docs.vac_del, name='day_off_del'),
    # ログイン
    url(r'^login/$', login.login_view, name='login'),
    # ログアウト
    url(r'^logout/$', views.logout_then_login, name='logout'),
    # プルダウンの動的変更
    url(r'^pulldown/(?P<type>\w+)/(?P<select_id>\d+)/(?P<next_id>\d+)', pulldown.pulldown, name='pulldown'),
]

jsl_vacation/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from api.urls import router as api_router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('vac.urls', namespace='vac')),
    url(r'^api/', include('api.urls', namespace='api')),
]

jsl_vacation/vac/urls.py
from django.conf.urls import url
from django.contrib.auth import views

from vac.views import list, menu, vac_docs, login, pulldown

urlpatterns = [
    # 休暇一覧表示
    url(r'^list/$', list.DayOffListView.as_view(), name='vacation_list'),
    # メニュー
    url(r'^$', menu.menu, name='vacation_menu'),
    # 新規休暇届
    url(r'^day_off/add/$', vac_docs.vac_edit, name='day_off_add'),
    # 休暇届修正
    url(r'^day_off/edit/(?P<day_off_id>\d+)$', vac_docs.vac_edit, name='day_off_edit'),
    # 休暇届削除
    url(r'^day_off/del/(?P<day_off_id>\d+)$', vac_docs.vac_del, name='day_off_del'),
    # ログイン
    url(r'^login/$', login.login_view, name='login'),
    # ログアウト
    url(r'^logout/$', views.logout_then_login, name='logout'),
    # プルダウンの動的変更
    url(r'^pulldown/(?P<type>\w+)/(?P<select_id>\d+)/(?P<next_id>\d+)', pulldown.pulldown, name='pulldown'),
]

vac/urls.py
from django.conf.urls import url
from django.contrib.auth import views

from vac.views import list, menu, vac_docs, login, pulldown

urlpatterns = [
    # 休暇一覧表示
    url(r'^list/$', list.DayOffListView.as_view(), name='vacation_list'),
    # メニュー
    url(r'^$', menu.menu, name='vacation_menu'),
    # 新規休暇届
    url(r'^day_off/add/$', vac_docs.vac_edit, name='day_off_add'),
    # 休暇届修正
    url(r'^day_off/edit/(?P<day_off_id>\d+)$', vac_docs.vac_edit, name='day_off_edit'),
    # 休暇届削除
    url(r'^day_off/del/(?P<day_off_id>\d+)$', vac_docs.vac_del, name='day_off_del'),
    # ログイン
    url(r'^login/$', login.login_view, name='login'),
    # ログアウト
    url(r'^logout/$', views.logout_then_login, name='logout'),
    # プルダウンの動的変更
    url(r'^pulldown/(?P<type>\w+)/(?P<select_id>\d+)/(?P<next_id>\d+)', pulldown.pulldown, name='pulldown'),
]

jsl/vac/models/day_off.py
from django.db import models
from datetime import time


from vac.models.vacation import Vacation


class DayOff(models.Model):

    DAYOFF_TYPE_PAID_HOLIDAY = 10
    DAYOFF_TYPE_HALF_PAID_HOLIDAY_AM = 20
    DAYOFF_TYPE_HALF_PAID_HOLIDAY_PM = 30
    DAYOFF_TYPE_SPECIAL = 40
    DAYOFF_TYPE_ABSENCE = 50
    DAYOFF_TYPE_HALF_ABSENCE = 60
    DAYOFF_TYPE_LIMIT_PAID_HOLIDAY = 70

    REASON_TYPE_SICK = 10
    REASON_TYPE_HOUSE_WORK = 20
    REASON_TYPE_AUSPICIOUS = 30
    REASON_TYPE_CONDOLENCE = 40
    REASON_TYPE_OTHER = 50

    DETAIL_TYPE_MARRY = 10
    DETAIL_TYPE_MARRY_CHILD = 20
    DETAIL_TYPE_BIRTH = 30
    DETAIL_TYPE_CONDOLENCE = 40

    DAYOFF_TYPE_CHOICE = (
        (DAYOFF_TYPE_PAID_HOLIDAY, "有給休暇"),
        (DAYOFF_TYPE_HALF_PAID_HOLIDAY_AM, "半日休暇(午前)"),
        (DAYOFF_TYPE_HALF_PAID_HOLIDAY_PM, "半日休暇(午後)"),
        (DAYOFF_TYPE_SPECIAL, "特別休暇"),
        (DAYOFF_TYPE_ABSENCE, "欠勤"),
        (DAYOFF_TYPE_HALF_ABSENCE, "半日欠勤"),
        (DAYOFF_TYPE_LIMIT_PAID_HOLIDAY, "時間制限有給休暇"),
    )

    REASON_TYPE_CHOICE = (
        (REASON_TYPE_SICK, "病気"),  # 有給など
        (REASON_TYPE_HOUSE_WORK, "家事都合"),  # 有給など
        (REASON_TYPE_AUSPICIOUS, "慶事"),  # 特別休暇
        (REASON_TYPE_CONDOLENCE, "弔事"),  # 特別休暇
        (REASON_TYPE_OTHER, "その他"),
    )

    DETAIL_TYPE_CHOICE = (
        (DETAIL_TYPE_MARRY, "本人が結婚"),  # 慶事・弔事
        (DETAIL_TYPE_MARRY_CHILD, "本人の子供が結婚"),  # 慶事・弔事
        (DETAIL_TYPE_BIRTH, "配偶者の出産"),  # 慶事・弔事
        (DETAIL_TYPE_CONDOLENCE, "弔事(配偶者・実父母・実養子・祖父母・配偶者の父母・兄弟姉妹・孫)"),  # 弔事
    )

    TIME_CHOICE = (
        (time(8, 30, 00), "8:30"),
        (time(9, 00, 00), "9:00"),
        (time(9, 30, 00), "9:30"),
        (time(10, 00, 00), "10:00"),
        (time(10, 30, 00), "10:30"),
        (time(11, 00, 00), "11:00"),
        (time(11, 30, 00), "11:30"),
        (time(12, 00, 00), "12:00"),
        (time(12, 30, 00), "12:30"),
        (time(13, 00, 00), "13:00"),
        (time(13, 30, 00), "13:30"),
        (time(14, 00, 00), "14:00"),
        (time(14, 30, 00), "14:30"),
        (time(15, 00, 00), "15:00"),
        (time(15, 30, 00), "15:30"),
        (time(16, 00, 00), "16:00"),
        (time(16, 30, 00), "16:30"),
        (time(17, 00, 00), "17:00"),
        (time(17, 30, 00), "17:30"),
    )

    the_year = models.IntegerField('年度')
    user = models.ForeignKey('vac.User', verbose_name='ユーザー', related_name='vac')

    day_off_type = models.IntegerField('区分', blank=False, null=True, choices=DAYOFF_TYPE_CHOICE)
    reason_type = models.IntegerField('事由', blank=False, null=True, choices=REASON_TYPE_CHOICE)
    detail_type = models.IntegerField('事由・詳細', blank=True, null=True, default=None, choices=DETAIL_TYPE_CHOICE)

    apply_day = models.DateField('届出日', blank=False, null=True)
    start_day = models.DateField('開始日', blank=True, null=True)
    end_day = models.DateField('終了日', blank=True, null=True)
    start_time = models.TimeField('開始時間', blank=True, null=True, choices=TIME_CHOICE)
    end_time = models.TimeField('終了時間', blank=True, null=True, choices=TIME_CHOICE)

    working_holiday = models.DateField('休出日', blank=True, null=True)
    compensatory_holiday = models.DateField('代休日', blank=True, null=True)
    transfer_day = models.DateField('振替日', blank=True, null=True)
    working_day = models.DateField('出勤日', blank=True, null=True)
    vacation_days = models.IntegerField('休暇日数', blank=True, null=True, default=0)
    total_days = models.IntegerField('合計日数', blank=True, null=True, default=0)
    total_time = models.IntegerField('合計時間', blank=True, null=True, default=0)
    used_days = models.IntegerField('使用日数', blank=True, null=True, default=0)
    used_time = models.IntegerField('使用時間', blank=True, null=True, default=0)
    rest_days = models.IntegerField('残日数', blank=True, null=True, default=0)
    rest_time = models.IntegerField('残時間', blank=True, null=True, default=40)

    comment = models.TextField('コメント', blank=True, null=True)

    def __str__(self):
        return self.user.username if self.user else ''

    # @classmethod
    # def day_off_type(cls, day_off_type):
    #     if day_off_type in [
    #                         cls.DAYOFF_TYPE_PAID_HOLIDAY,
    #                         cls.DAYOFF_TYPE_HALF_PAID_HOLIDAY_AM,
    #                         cls.DAYOFF_TYPE_HALF_PAID_HOLIDAY_PM,
    #                         cls.DAYOFF_TYPE_ABSENCE,
    #                         cls.DAYOFF_TYPE_HALF_ABSENCE,
    #                         cls.DAYOFF_TYPE_LIMIT_PAID_HOLIDAY,
    #                         ]:#有給休暇、半日有給(午前)、半日有給(午後)、欠勤、半日欠勤、時間指定有給休暇の場合
    #         return [
    #                 cls.REASON_TYPE_SICK,
    #                 cls.REASON_TYPE_HOUSE_WORK,
    #                 cls.REASON_TYPE_OTHER
    #                 ]
    #     elif day_off_type == cls.DAYOFF_TYPE_SPECIAL:#特別休暇の場合
    #         return [cls.REASON_TYPE_AUSPICIOUS,
    #                 cls.REASON_TYPE_CONDOLENCE,
    #                 cls.REASON_TYPE_OTHER,]
    #
    #
    # def get_reason_type(cls, reason_type):
    #      if reason_type in [
    #          cls.REASON_TYPE_AUSPICIOUS,
    #          cls.REASON_TYPE_CONDOLENCE,
    #      ]:#理由が慶次か弔辞の場合
    #          return [
    #          cls.DETAIL_TYPE_MARRY,
    #          cls.DETAIL_TYPE_MARRY_CHILD,
    #          cls. DETAIL_TYPE_BIRTH,
    #          ]
    #      elif reason_type== cls._TYPE_CONDOLENCE:#弔辞の場合
    #          return[
    #              cls.DETAIL_TYPE_CONDOLENCE
    #          ]
    #      else:#それ以外の場合
    #          return



    # def clean(self):
    #     reason_clean = self.cleaned_data.get(DayOff.day_off_type)
    #     detail_clean = self.cleaned_data.get(DayOff.reason_type)

jsl/vac/models/section.py
from django.db import models


class Section(models.Model):
    name = models.CharField('所属名', max_length=255, blank=True, null=True)
    order = models.IntegerField('ソート順', blank=True, null=True)

    def __str__(self):
        return self.name

jsl/vac/models/vacation.py
from django.db import models


class Vacation(models.Model):
    the_year = models.IntegerField('年度', default=0)
    user = models.ForeignKey('vac.User', verbose_name='ユーザー', related_name='vacations')
    transfer_days = models.IntegerField('繰越日数', default=0)
    grant_days = models.IntegerField('付与日数', default=0)
    total_days = models.IntegerField('合計日数', default=0)
    used_days = models.IntegerField('使用日数', default=0)
    used_time = models.IntegerField('使用時間', default=0)
    rest_days = models.IntegerField('残日数', default=0)
    rest_time = models.IntegerField('残時間', default=40)
    absence_days = models.IntegerField('欠勤日数', default=0)

    # def __str__(self):
    #     return self.name

jsl/vac/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth import authenticate, login
from vac.models import DayOff, Section, User, Vacation


class LoginForm(ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(render_value=False,
                                                          attrs={'class': 'form-control', 'placeholder': 'Password'}))
    remember = forms.BooleanField(label="Remember me",  help_text="セッションを保存", required=False)

    user = None

    def clean(self):
        if self._errors:
            return
        user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])
        if user:
            if user.is_active:
                self.user = user
            else:
                raise forms.ValidationError('ユーザーは無効です')
        else:
            raise forms.ValidationError('invalid username of password.')
        return self.cleaned_data

    def login(self, request):
        if self.is_valid():
            login(request, self.user)
            if self.cleaned_data['remember']:
                request.session.set_expiry(60 * 60 * 24 * 365 * 5)  # セッションの有効期限を5年とする.
            else:
                request.session.set_expiry(0)  # セッションはブラウザを閉じた時に破棄される
            return True
        return False

    class Meta:
        model = User
        fields = ('username', 'password', )


class DayOffForm(ModelForm):
    """DayOffのフォーム"""
    class Meta:
        model = DayOff
        fields = ('day_off_type', 'reason_type',
                  'detail_type', 'start_day', 'end_day',
                  'start_time', 'end_time', )


class SectionForm(ModelForm):
            """Sectionのフォーム"""
            class Meta:
                model = Section
                fields = ('name', 'order')


class UserForm(ModelForm):
            """Userのフォーム"""

            class Meta:
                model = User
                fields = ('employee_id', 'employee_name', 'section',
                          'regular_entry_date', 'job_entry_date',
                          'continuous_years', 'is_retirement',)


class VacationForm(ModelForm):
            """Vacationのフォーム"""

            class Meta:
                model = Vacation
                fields = ('the_year', 'user', 'transfer_days', 'grant_days',
                          'total_days', 'used_days','used_time',  'rest_days', 'rest_time',
                          'absence_days',)

jsl/vac/views.py
from django.shortcuts import render

# Create your views here.

jsl/vac/views/list.py
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from vac.models.day_off import DayOff


@method_decorator(login_required, name='dispatch')
class DayOffListView(ListView):
    context_object_name = 'day_offs'
    template_name = 'vac/vac_list.html'
    paginate_by = 8

    def get(self, request, *args, **kwargs):
        the_year = request.GET.get('the_year', '')
        user_employee_id = request.GET.get('user_employee_id', '')
        day_offs = DayOff.objects.select_related('user').all()
        if the_year:
            day_offs = day_offs.filter(the_year=the_year)
        if user_employee_id:
            day_offs = day_offs.filter(user__employee_id=user_employee_id)
        day_offs = day_offs.order_by('-id')
        self.object_list = day_offs

        context = self.get_context_data(object_list=self.object_list,
                                        the_year=the_year,
                                        user_employee_id=user_employee_id)
        return self.render_to_response(context)

jsl/vac/views/login.py
from django.shortcuts import render, redirect


from vac.forms import LoginForm


def login_view(request):
    """ログイン"""

    """
    ログイン状態でメニューへリダイレクトされません
    if request.user.is_authenticated():
        return redirect('vac:vacation_menu')
    """

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            if form.login(request):
                if 'next' in request.GET:
                    return redirect(request.GET['next'])
                else:
                    return redirect('vac:vacation_menu')
    else:
        form = LoginForm()

    return render(request, 'vac/login.html', dict(form=form))

jsl/vac/views/menu.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def menu(request):
    # return HttpResponse('休暇管理システムメニュー')
    return render(request, 'vac/index.html')

jsl/vac/views/pulldown.py
from django.http import HttpResponse
from django.shortcuts import redirect

from vac.models import DayOff


def pulldown(request, type, select_id, next_id):
    select_id = int(select_id)
    reason = DayOff.REASON_TYPE_CHOICE
    detail = DayOff.DETAIL_TYPE_CHOICE
    remarks = []
    if type == "dayoff":
        if select_id in {DayOff.DAYOFF_TYPE_PAID_HOLIDAY, DayOff.DAYOFF_TYPE_HALF_PAID_HOLIDAY_AM,
                         DayOff.DAYOFF_TYPE_HALF_PAID_HOLIDAY_PM, DayOff.DAYOFF_TYPE_ABSENCE,
                         DayOff.DAYOFF_TYPE_HALF_ABSENCE, DayOff.DAYOFF_TYPE_LIMIT_PAID_HOLIDAY}:
            id_list = [
                DayOff.REASON_TYPE_SICK,
                DayOff.REASON_TYPE_HOUSE_WORK,
                DayOff.REASON_TYPE_OTHER
            ]
            if select_id == DayOff.DAYOFF_TYPE_LIMIT_PAID_HOLIDAY:
                remarks.append("time_able")
        elif select_id in {DayOff.DAYOFF_TYPE_SPECIAL}:
            id_list = [
                DayOff.REASON_TYPE_AUSPICIOUS,
                DayOff.REASON_TYPE_CONDOLENCE,
                DayOff.REASON_TYPE_OTHER
            ]
        else:
            id_list = []
        return HttpResponse(create_options(id_list, reason, next_id, type, remarks))
    elif type == "reason":
        if select_id in {DayOff.REASON_TYPE_AUSPICIOUS, DayOff.REASON_TYPE_CONDOLENCE}:
            id_list = [
                DayOff.DETAIL_TYPE_MARRY,
                DayOff.DETAIL_TYPE_MARRY_CHILD,
                DayOff.DETAIL_TYPE_BIRTH
            ]
            if select_id == DayOff.REASON_TYPE_CONDOLENCE:
                id_list.append(DayOff.DETAIL_TYPE_CONDOLENCE)

            remarks.append("detail_able")
        else:
            id_list = []
        return HttpResponse(create_options(id_list, detail, next_id, type, remarks))
    else:
        return redirect("vac:logout")


def create_options(ids_list, choice, next_id, type, remarks):
    _name_ = "reason_type" if type == "dayoff" else "detail_type"
    _id_ = "id_" + _name_
    disp_html = ['<select name="' + _name_ + '" class="form-control" required id="' + _id_ + '">\n']
    for elem in ids_list:
        selected = 'selected' if elem == int(next_id) else ''
        disp_html.append('<option value="' + str(elem) + '" ' + selected + '>' + choice[int(elem/10)-1][1] + '</option>\n')

    selected = 'selected' if next_id == '0' else ''
    disp_html.insert(1, "<option value " + selected + ">---------</option>\n")
    disp_html.append("</select>\n")

    for remark in remarks:
        disp_html.append("<!-- " + remark + " -->\n")
    return disp_html

jsl/vac/templates/vac/index.html
{% extends "base.html" %}
{% load bootstrap %}
<head>
{% include "nav_head.html" %}
</head>

{% block extrahead %}
{% include "nav_bar.html" %}
    <style>
        .wrapper {
            max-width: 500px;
            margin: 0 auto;
        }
    </style>
{% endblock extrahead %}



{% block title %}休暇管理システムメニュー{% endblock title %}

{% block content %}
{% include "nav_bar.html" %}
    <div class="wrapper">
        <h3 class="page-header">休暇管理システムメニュー</h3>
        <p><a href="{% url 'vac:day_off_add' %}" class="btn btn-primary btn-lg btn-block">新規休暇届入力</a></p>
        <p><a href="{% url 'vac:vacation_list' %}" class="btn btn-default btn-lg btn-block">休暇届一覧</a></p>
    </div>
{% endblock content %}

jsl/vac/templates/vac/login.html
{% extends "base.html" %}
{% load bootstrap %}
{% block extrahead %}
    <style>
        .wrapper {
            max-width: 350px;
            padding: 30px 40px 50px 40px;
            margin: 0 auto 25px;
            margin-top: 8%;
            background: #f7f7f7;
            box-shadow: 0 2px 2px rgba(0, 0, 0, 0.3);
            border-radius: 2px;
        }
        .login_user {
            text-align: center;
        }
        .buttons {
            width: 100px;
            margin-top: 20px;
        }
        .page-header {
            text-align: center;
        }
        .login {
            margin-bottom: 30px;
        }

        /* 幅が320px以下のデバイスのみ実行 */
        @media screen and (max-width: 320px) {
            .page-header {
                font-size: 23px;
            }
        }
    </style>
{% endblock extrahead %}

{% block title %}ログイン{% endblock %}

{% block content %}
    <div class="wrapper">
        <form action="" method="post" class="form-signin">
            {% csrf_token %}
            <h3 class="page-header">JSL休暇届システム</h3>

            {% if form.errors %}
                <div class="alert alert-danger" role="alert">Invalid Username or Password.</div>
            {% endif %}


            {% if user.is_authenticated %}
                <div class="login_user">
                    現在, {{ user }} さんとしてログイン中です。<br>
                    <a href="{% url 'vac:vacation_menu' %}" class="btn btn-default buttons">メニュー</a><br>
                    <a href="{% url 'vac:logout' %}" class="btn btn-danger buttons">ログアウト</a>
                </div>
            {% else %}
                {{ form.username }}
                {{ form.password }}

                <div class="checkbox">
                    <label for="id_remember" class="checkbox-inline">{{ form.remember }}{{ form.remember.help_text }}</label>
                </div>

                <input type="submit" value="ログイン" class="btn btn-primary btn-block login">

            {% endif %}
        </form>
    </div>
{% endblock content %}

jsl/vac/templates/vac/logout.html
{% extends "base.html" %}
{% load bootstrap %}

{% block extrahead %}
    <style>
        .wrapper{
            text-align: center;
        }
    </style>
{% endblock extrahead %}

{% block title %}ログアウト{% endblock title %}

{% block content %}
    <div class="wrapper">
        <h3 class="page-header">ログアウトしました</h3>
        <a href="{% url 'vac:login' %}" class="btn btn-primary">ログイン</a>
    </div>
{% endblock content %}

jsl/vac/templates/vac/vac_list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %} 休暇一覧 {% endblock title %}

{% block extrahead %}
{% include "nav_bar.html" %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
    table {
        margin-top: 8px;
    }

    th { white-space: nowrap; }
    td { white-space: nowrap; height: 51px; }
    .list-table { overflow-x: scroll; }
    .lock-list-table {
        float: left;
    }
    .lock-list-table table {
        font-weight: 600;
    }
</style>
{% endblock %}
<head>
    {% include "nav_head.html" %}
</head>
{% block content %}
{% include "nav_bar.html" %}

    <ol class="breadcrumb" style="display: inline-block;">
        <li><a href="{% url 'vac:vacation_menu' %}">メニュー</a></li>
        <li>休暇一覧</li>
    </ol>
    <h3 class="page-header">休暇一覧
        <small><div align="right">
            ユーザー名 : {{ user.employee_name }}&emsp;&emsp;
        </div></small>
    </h3>
    <form action="" method="GET" name="search_form" class="form-inline">
    <div class="form-group">
        <label>年度(西暦)</label>
        <input type="number" name="the_year" placeholder="yyyy" class="form-control" value="{{ the_year }}">
        <label>社員番号</label>
        <input type="char" name="user_employee_id" placeholder="000000" class="form-control" value="{{ user_employee_id }}">
        <button type="SUBMIT" class="btn btn-default">検索</button>
    </div>
    </form>
    <div class="lock-list-table">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>社員番号</th>
                    <th>氏名</th>
                </tr>
            </thead>
            <tbody>
                {% for day_off in day_offs %}
                    <tr>
                        <td>{{ day_off.user.employee_id|default_if_none:"" }}</td>
                        <td>{{ day_off.user.employee_name|default_if_none:"" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="list-table">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>届け日</th>
                    <th>休暇日From</th>
                    <th>休暇日To</th>
                    <th>休暇時間From</th>
                    <th>休暇時間to</th>
                    <th>区分</th>
                    <th>事由</th>
                    <th>修正/削除</th>
                </tr>
            </thead>
            <tbody>
                {% for day_off in day_offs %}
                    <tr>
                        <td>{{ day_off.apply_day|default_if_none:"" }}</td>
                        <td>{{ day_off.start_day|default_if_none:"" }}</td>
                        <td>{{ day_off.end_day|default_if_none:"" }}</td>
                        <td>{{ day_off.start_time|default_if_none:"" }}</td>
                        <td>{{ day_off.end_time|default_if_none:"" }}</td>
                        <td>{{ day_off.get_day_off_type_display|default_if_none:"" }}</td>
                        <td>{{ day_off.get_reason_type_display|default_if_none:"" }}</td>
                        <td>
                            <a href="{% url 'vac:day_off_edit' day_off_id=day_off.id %}" class="btn btn-default">修正</a>
                            <button class="btn btn-danger del_confirm" data-toggle="modal"
                                    data-target="#deleteModal" pk="{{ day_off.id }}"
                                    url="{% url 'vac:day_off_del' day_off_id=day_off.id %}">削除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}
    <div class="pull-right">
        <a href="{% url 'vac:day_off_add' %}" class="btn btn-primary">新規申請</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">確認</h4>
      </div>
      <div class="modal-body">
        <p>削除しますか？</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}